version: '3'

services:
    fa_db:
        image: mysql:5.6
        restart: always
        container_name: fa_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=IprOMASHaRYWAVAUREAc
            - MYSQL_DATABASE=front_acc_db
        volumes:
            - /opt/fa/data:/var/lib/mysql
        networks:
            fa_network:
                aliases:
                    - fa_db   
    front_acc:
        depends_on:
            - fa_db
        image: genebarker/frontaccounting
        container_name: front_acc
        command: ["--http"]
        build: .
        restart: always
        volumes:
            - /opt/fa/web_app:/var/www/html
            - /opt/fa/ssl:/etc/ssl 
        ports:
            - '8085:80'
        networks:
            fa_network:
                aliases:
                    - fa_app
networks:
    fa_network: 
        driver: bridge
